obj-$(CONFIG_CKERNEL_DRIVER) += ckernel.o

ckernel-y := \
	ckernel_main.o \
	ckernel_mbm.o \
	ckernel_apparmor.o \
	ckernel_acct.o \
	ckernel_socket_domain.o \
	ckernel_shmem_cache.o \
	ckernel_vfs_cache.o \
	ckernel_proc.o \
	ckernel_debugfs.o
