# SPDX-License-Identifier: GPL-2.0
CFLAGS += -O2 -Wall -Wextra
all: ckmctl maple_probe maple_pair ckm_mount_prepare vfs_pair socket_owner_cost
clean:
	$(RM) ckmctl maple_probe maple_pair ckm_mount_prepare vfs_pair socket_owner_cost
.PHONY: all clean
